<?php

/**
 * This is the model base class for the table "staff_role".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "StaffRole".
 *
 * Columns in table "staff_role" available as properties of the model,
 * followed by relations of table "staff_role" available as properties of the model.
 *
 * @property integer $id
 * @property string $description
 * @property string $cpm
 *
 * @property Staff[] $staffs
 */
abstract class BaseStaffRole extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'staff_role';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'StaffRole|StaffRoles', $n);
	}

	public static function representingColumn() {
		return 'description';
	}

	public function rules() {
		return array(
			array('description, cpm', 'required'),
			array('description', 'length', 'max'=>256),
			array('cpm', 'length', 'max'=>4),
			array('id, description, cpm', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'staffs' => array(self::HAS_MANY, 'Staff', 'staff_role_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'description' => Yii::t('app', 'Description'),
			'cpm' => Yii::t('app', 'Cpm'),
			'staffs' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('cpm', $this->cpm, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}