<?php

/**
 * This is the model base class for the table "staff".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Staff".
 *
 * Columns in table "staff" available as properties of the model,
 * followed by relations of table "staff" available as properties of the model.
 *
 * @property integer $id
 * @property integer $person_id
 * @property integer $staff_role_id
 *
 * @property Person $person
 * @property StaffRole $staffRole
 */
abstract class BaseStaff extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'staff';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Staff|Staffs', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('person_id, staff_role_id', 'required'),
			array('person_id, staff_role_id', 'numerical', 'integerOnly'=>true),
			array('id, person_id, staff_role_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'person' => array(self::BELONGS_TO, 'Person', 'person_id'),
			'staffRole' => array(self::BELONGS_TO, 'StaffRole', 'staff_role_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'person_id' => null,
			'staff_role_id' => null,
			'person' => null,
			'staffRole' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('person_id', $this->person_id);
		$criteria->compare('staff_role_id', $this->staff_role_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}